f = open('C:/work/pyzen.txt','wt')
f.write('at 모드 테스트\n')
f.write('추가: 아름다운이 추한 것보다 낫다.\n')
f.write('추가: 명시적인 것이 암묵적인 것보다 낫다. \n')
f.close()

f = open('C:/work/pyzen.txt',mode='r')
s = f.read()
print(s) 
f.close()